### ISSUE TITLE
Can the source organization be specified

### ISSUE THREAD

**Issue by kafka-jh** [person-c/easybio#17]
Hello, this work is very interesting and I was wondering if it is possible to specify the cell source just like Cellmarker 2.0 can specify the tissue and organ so that the results are more accurate for specific cell types

**Comment by person-c** [comment]
> Hello, this work is very interesting and I was wondering if it is possible to specify the cell source just like Cellmarker 2.0 can specify the tissue and organ so that the results are more accurate for specific cell types

Thanks, now it can specify tissueClass and tissueType; You can view all  available tissue by function ` available_tissue_type()` and ` available_tissue_class()`
