### ISSUE TITLE
Run easybio R package error

### ISSUE THREAD

**Issue by Sisov** [person-c/easybio#18]
Hello, this is a good software for the cell annotation, while run the matchCellMarker2 there have a error:
matched_markers <- matchCellMarker2(pbmc.markers, n = 50, spc = "Human"):
Error in let(uniqueN = sapply(markerWith, FUN = function(x) uniqueN(x))), there have let functions
Did there have any solutions to address it?
Thanks

**Comment by person-c** [comment]
It's hard to guess what error happpend from your code. It's suggested to provide the full code and error messages.

**Comment by Sisov** [comment]
Sorry, the detail error like that:
![微信图片_20240929203901](https://github.com/user-attachments/assets/4e459dfc-a0ef-4587-bfb8-5bbf3a460146)

**Comment by person-c** [comment]
The `let()` function is implemented in data.table [v1.15.0](https://github.com/Rdatatable/data.table/milestone/29) (30 Jan 2024). Run the following code to update this pacakge, and try again.

```r
data.table::update_dev_pkg()
```
